### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by dausruddin** [apm1467/videocr#24]
Hi. I am trying this project with a couple of videos, but none of them work. teserract hammer my CPU, but no output can I see.

**Comment by p2635** [comment]
Yeah I tried it for 10 minutes or so and still didn't get any results either. Maybe it's not actively maintained.

**Comment by xcymax** [comment]
How long are the videos you are testing? 

I ran a 23minute .avi (175mb) video on my AMD Ryzen 7 3700X (8 core 16 thread) and it took ~11minutes to fully process at 100% CPU load.

**Comment by dausruddin** [comment]
To be honest, I already forgot about those details. So I'll close this issue until I try this program again.

Thanks.
